# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpdService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UpdService
pod 'OpenCV', '~> 3.4.2'
pod 'CocoaAsyncSocket', '~> 7.6.3'

end
